add tests

diff --git a/git-alias b/git-alias
--- a/git-alias
+++ b/git-alias
@@ -1,4 +1,4 @@
-get_branch() {
+get_branch_old() {
 	local branch=$(git symbolic-ref HEAD 2>/dev/null |awk -F / '{print $3}')
 	#local branch=$(git name-rev --name-only HEAD)
 	if [ -z "${branch}" ]; then
@@ -23,6 +23,36 @@ get_branch() {
 	fi
 }
 
+get_branch() {
+	# try @{upstream} first since it is easy
+	upstream=$(git name-rev @{upstream} --name-only 2>/dev/null)
+	if [ -z "${upstream}" ]; then
+		upstream=$(git log --oneline  -n 50 |grep git5track |head -1 |cut -f 1 -d " ")
+	fi
+	if [ -n "${upstream}" ]; then
+		echo ${upstream}
+		return
+	fi
+	# maybe we are in the middle of a rebase
+	upstream=$(git name-rev @{-1} --name-only)
+	echo "Warning: Using upstream branch ${upstream}" >/dev/stderr
+
+	local remote=$(git config -l | \
+		sed -n "s#branch.${upstream}.remote=\(.*\)#\1#p")
+	local merge=$(git config -l | \
+		sed -n "s#branch.${upstream}.merge=refs/heads/\(.*\)#\1#p")
+	[ -n "${remote}${merge}" ] || (
+		echo "Error: No tracking branch" >/dev/stderr;
+		echo "Use 'git branch --set-upstream ${upstream} upstream/foo'" \
+			>/dev/stderr;
+		echo >/dev/stderr;
+		return 1)
+	if [ "${remote}" == "." ]; then
+		echo ${merge}
+	else
+		echo ${remote}/${merge}
+	fi
+}
 
 # show changed made in top commit (useful when working through a rebase -i)
 alias dh='git diff HEAD~'
@@ -34,8 +64,17 @@ alias rs='git rebase --skip'
 # add all changed files
 alias au='git add -u'
 
+
+git_log_oneline() {
+	if [ $# -eq 0 ]; then
+		git log --oneline --decorate $(get_branch).. $@
+	else
+		git log --oneline --decorate $@
+	fi
+}
+
 # show short list of commits in this branch
-alias ol='git log --oneline --decorate $(get_branch)..'
+alias ol='git_log_oneline'
 
 # show stat log of commits in this branch
 alias sl='git log --stat $(get_branch)..'
@@ -71,7 +110,7 @@ alias gr='interactive_rebase'
 
 function next_commit_changes()
 {
-	out=$(git log --numstat --pretty=format: -n1 | tail -n+2)
+	out=$(git log --numstat --pretty=format: -n1 | tail -n+1)
 	echo "$out" | awk '{printf("%s ", $3)}'
 }
 
@@ -112,5 +151,62 @@ function show_commit()
 {
 	git diff $1~..$1
 }
-alias gd='show_commit'
+alias sd='show_commit'
+alias gd='git diff'
+alias gdc='git diff --cached'
 alias gc='git commit'
+alias co='git checkout'
+
+function do_tag_archive()
+{
+	git show $1 |head -5 && git tag archive/$1-$(date +%d-%b-%y) $1 && git branch -D $1
+}
+
+alias tag_archive='do_tag_archive $1'
+
+alias gl='git log'
+alias glo='git log --oneline --decorate'
+
+# set_upstream [upstream_branch]
+# Sets the upstream branch for the current branch
+# If arg is omitted, will use m/master
+function set_upstream()
+{
+	branch=$(git name-rev HEAD --name-only)
+
+	upstream=${1-m/master}
+#	echo ${upstream} ${branch}
+	if [ -n ${branch} ]; then
+#		if ! git branch --set-upstream-to ${branch}/${upstream}; then
+		git branch --set-upstream-to ${upstream} ${branch}
+#		     	echo bad
+#			commits=$(glo -n100 |grep -n git5 | sed 's/:.*//')
+#			echo ${commits}
+#			git branch -D us-git5
+#			git branch us-git5 HEAD~$(($commits - 1))
+#		fi
+	else
+		echo "Cannot test current branch"
+	fi
+}
+
+alias us='set_upstream'
+alias et='git rebase --edit-todo'
+
+
+function fix_kconfig()
+{
+	crosfw -b $1 -w && \
+	make O=b/$1 savedefconfig && \
+	meld b/$1/defconfig configs/$1_defconfig
+}
+
+alias fix-kconfig='fix_kconfig'
+
+alias pe='git log --oneline -n10 --decorate'
+
+alias pm='patch -p1 --merge <.git/rebase-apply/patch'
+
+alias good='git bisect good'
+alias bad='git bisect bad'
+
